
import type { Metadata } from "next";
import Header from "@/layout/header";
import Footer from "@/layout/footer";
import Aside from "@/layout/aside";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<Readonly<{ children: React.ReactNode }>> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <Header />
        <div className="flex flex-1">
          <Aside />
          {children}
        </div>
        <Footer /> 
      </body>
    </html>
  );
};

export default RootLayout;